<div class="section-wrapper">
    <div class="header">
        <div class="title">
            <h1>Contactos</h1>
        </div>
        <div class="actions">
            <a style="margin-left:20px" href="#" >Importar desde excel</a>
            <style>.section-wrapper .header { position: relative }</style>
            <a id="downloadClients" style="position: absolute;right: 14px;bottom: 13px;color: rgb(167, 164, 164);" href="#">Exportar</a>
        </div>
    </div>
    <div class="content"></div>
</div>

<div id="contacts_store">
</div>