<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/html" class="x-border-box x-strict">
    <head>
        <!-- End Google Tag Manager -->
        <meta http-equiv="X-UA-Compatible" content="chrome=1">
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
        <link rel="stylesheet" type="text/css" href="https://cdn1.alegra.com/long-term/compressed/ext-theme-gray-all2.css">
        <link type="image/x-icon" rel="shortcut icon" href="https://cdn1.alegra.com/images/favicon.ico">
        <link rel="stylesheet" type="text/css" href="https://cdn1.alegra.com/public/f659e7974d744ffbf02d4a7528e7ea84/compressed/styles-min.css">

        <script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/Big.min.js"></script>
        <!-- <script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/ext-all.js"></script> -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/extjs/4.2.1/ext-all.min.js"></script>
        <script type="text/javascript" src="/app.js"></script>
        <script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/ext-lang-es.js"></script>
        <!--End of Zopim Live Chat Script-->
        <title>Contactos</title>
        <meta id="wwi3bdi87sg87gi3av8bc8sgeyvru2y3">
        
        <style media="print" class="jx_ui_StyleSheet" __jx__id="___$_2" type="text/css">.zopim { display: none !important }</style>
    </head>
    <body id="contact-index" class="x-body x-webkit x-chrome">
        <div class="zopim" __jx__id="___$_61 ___$_61" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; border: 0px; background: transparent; overflow: hidden; position: fixed; z-index: 16000002; width: 187px; height: 30px; right: 10px; bottom: 0px; display: none;"><iframe frameborder="0" src="about:blank" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 100%; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;"></iframe></div>
        <div class="zopim" __jx__id="___$_4 ___$_4" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; border: 0px; background: transparent; overflow: hidden; position: fixed; z-index: 16000001; right: 10px; bottom: 0px; border-top-left-radius: 5px; border-top-right-radius: 5px; display: none; width: 290px; height: 400px; box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 3px 2px;"><iframe frameborder="0" src="about:blank" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 100%; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;"></iframe></div>
        <!-- Google Tag Manager (noscript) -->
        <noscript>&lt;iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KQG46G"
            height="0" width="0" style="display:none;visibility:hidden"&gt;&lt;/iframe&gt;
        </noscript>
        <!-- End Google Tag Manager (noscript) -->
        <div class="main-container">
            <div style=" " class="header-wrapper">
                <div id="membership-notifications-wrapper" class="trial" data-user="72411">
                    <div class="membership-notification priority-low">
                        <div class="header">
                            <div class="title">
                                <h1>
                                                           
                                </h1>
                            </div>
                        </div>
                        <div class="footer"></div>
                    </div>
                </div>
                <div id="hints-wrapper-top">
                </div>
                <header style="">
                    <div class="logo" style="float:left; margin-top: 15px; margin-left:7px; margin-bottom: 3px;">
                        <a href="/">
                        <img src="https://cdn1.alegra.com/images/logo_alegra.png" style="width: 178px">
                        </a>
                        <a id="change-logo-link" class="change-logo" href="/company/edit">Utilizar mi logo</a>
                    </div>
                    <div id="search" class="search-input" style="float:left; margin-left: 86px; margin-top: 23px;">
                        <table class="x-field x-table-plain x-form-item x-field-default" cellpadding="0" id="combobox-1034" style="table-layout: fixed;">
                            <tbody>
                                <tr id="combobox-1034-inputRow">
                                    <td id="combobox-1034-labelCell" style="display:none;" valign="top" halign="left" width="105" class="x-field-label-cell"><label id="combobox-1034-labelEl" for="combobox-1034-inputEl" class="x-form-item-label x-unselectable x-form-item-label-left" style="width:100px;margin-right:5px;" unselectable="on"></label></td>
                                    <td class="x-form-item-body " id="combobox-1034-bodyEl" colspan="3" role="presentation" style="width: 150px;">
                                        <table id="combobox-1034-triggerWrap" class="x-form-trigger-wrap" cellpadding="0" cellspacing="0" style="width: 150px; table-layout: fixed;">
                                            <tbody>
                                                <tr>
                                                    <td id="combobox-1034-inputCell" class="x-form-trigger-input-cell" style="width: 100%;">
                                                        <div class="x-hide-display x-form-data-hidden" role="presentation" id="ext-gen1077"></div>
                                                        <input id="combobox-1034-inputEl" type="text" class="x-form-field x-form-empty-field x-form-text " autocomplete="off" name="combobox-1034-inputEl" placeholder="Buscar..." aria-invalid="false" data-errorqtip="" style="width: 100%;">
                                                    </td>
                                                    <td valign="top" class=" x-trigger-cell x-unselectable" style="width:17px;display:none;" id="ext-gen1076">
                                                        <div class="x-trigger-index-0 x-form-trigger x-form-arrow-trigger x-form-trigger-first" role="button" id="ext-gen1075"></div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <ul class="user-menu">
                        <li class="help"><a href="http://ayuda.alegra.com/hc/es" target="_blank">Ayuda</a></li>
                        <li class="support" id="support-link"><a href="">Soporte</a></li>
                        <li class="user"><a href="/user/view/id/1" title="tsu.nelsonmarcano@gmail.com - Desarrollo de Software">
                            tsu.nelsonmarcano@gmail...</a>
                        </li>
                        <li class="configuration"><a href="/configuration">Configuración</a></li>
                        <li class="logout"><a href="/user/log-out">Salir</a></li>
                    </ul>
                </header>
                <div id="app-contact-phone" style="height: 9px; width: 1024px; margin: 0 auto; position: relative; top: -23px; display: none;">
                    <div id="containerMx" style="border: 2px solid rgb(0, 190, 167); border-radius: 5px; padding: 0px 22px; float: right; background-color: rgb(0, 190, 167); color: white; margin-bottom: -17px;">
                        <p style="font-size: 12px; margin: 4px 0px;">Solicita ayuda al 
                        <address style="display: inline-block;">(+57) 1 508 8239</address>
                        </p>
                    </div>
                </div>
               
                <nav style="position: relative;">
                    <div style="width:1024px; margin: 0 auto">
                        <ul id="nav1" class="primary">
                            <li class=""><a href="/">Inicio</a></li>
                            <li class=" hasSubmenu ">
                                <a href="/invoice">Ingresos</a>
                                <ul class="secondary">
                                    <li><a href="/invoice">Cuentas de cobro</a></li>
                                    <li><a href="/recurring-invoice">Cuentas de cobro recurrentes</a></li>
                                    <li><a href="/transaction/retrieve-in">Pagos recibidos</a></li>
                                    <li><a href="/credit-note">Notas crédito</a></li>
                                    <li><a href="/estimate">Cotizaciones</a></li>
                                    <li><a href="/remission">Remisiones</a></li>
                                    <li><a href="/invoice/pos">POS</a></li>
                                </ul>
                            </li>
                            <li class=" hasSubmenu ">
                                <a href="/payment">Gastos</a>
                                <ul class="secondary">
                                    <li><a href="/payment">Pagos</a></li>
                                    <li><a href="/bill">Facturas de proveedores</a></li>
                                    <li><a href="/recurring-payment">Pagos  Recurrentes</a></li>
                                    <li><a href="/debit-note">Notas débito</a></li>
                                    <li><a href="/purchase-order">Órdenes de compra</a></li>
                                </ul>
                            </li>
                            <li class=" active active hasSubmenu ">
                                <a href="/index">Contactos</a>
                                <ul class="secondary">
                                    <li class="active"><a href="/index">Todos</a></li>
                                    <li><a href="/index/view-clients">Clientes</a></li>
                                    <li><a href="/index/view-providers">Proveedores</a></li>
                                </ul>
                            </li>
                            <li class=" hasSubmenu ">
                                <a href="/item">Inventario</a>
                                <ul class="secondary">
                                    <li><a href="/item">Items de venta</a></li>
                                    <li><a href="/report/inventory">Valor de Inventario</a></li>
                                    <li><a href="/inventory-adjustment">Ajustes a Inventario</a></li>
                                    <li><a href="/item/items-management">Gestión de Items</a></li>
                                    <li><a href="/price-list">Listas de precios</a></li>
                                    <li><a href="/warehouse">Bodegas</a></li>
                                </ul>
                            </li>
                            <li class=" hasSubmenu ">
                                <a href="/account">Bancos</a>
                                <ul class="secondary"></ul>
                            </li>
                            <li class=" hasSubmenu ">
                                <a href="/category">Categorías</a>
                                <ul class="secondary">
                                    <li><a href="/category">Categorías</a></li>
                                    <li><a href="/journal">Ajustes de Categorías</a></li>
                                </ul>
                            </li>
                            <li class=""><a class="menu-small" href="/report">Reportes</a></li>
                            <li id="quick-add-button-holder">
                                <div class="x-btn menu-button x-unselectable x-btn-default-medium x-icon-text-left x-btn-icon-text-left x-btn-default-medium-icon-text-left" style="border-width:1px;width:130px;height:48px;" id="splitbutton-1018">
                                    <div id="splitbutton-1018-btnWrap" class="x-btn-wrap x-btn-split x-btn-split-right" unselectable="on" style="height: 41px;"><a id="splitbutton-1018-btnEl" class="x-btn-button" role="button" hidefocus="on" unselectable="on" tabindex="0" style="height: 41px;"><span id="splitbutton-1018-btnInnerEl" class="x-btn-inner x-btn-inner-center" unselectable="on" style="line-height: 41px;">Nuevo</span><span role="img" id="splitbutton-1018-btnIconEl" class="x-btn-icon-el icon-add " unselectable="on" style="">&nbsp;</span></a></div>
                                </div>
                            </li>
                        </ul>
                        <div id="quick-add-button-holder"></div>
                    </div>
                </nav>
            </div>
            <div id="notification-wrapper"></div>
            <div class="main-wrapper">
                <div id="alegra_content" class="main-content">
                    <?php  echo $this->layout()->content ?>
                </div>
            </div>
            <div class="footer-wrapper">
                <footer>
                    <div id="ayuda" class="box">
                        <h4>Ayudas paso a paso</h4>
                        <ul class="vineta">
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/205798409-C%C3%B3mo-hacer-una-Factura-de-venta-" class="initWalkthru" data-walktrhu-name="createInvoice" data-walkthru-id="17946" target="_blank">Cómo crear una cuenta de cobro</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/206509365--C%C3%B3mo-crear-una-Factura-de-Proveedor-" class="initWalkthru" data-walktrhu-name="createBill" data-walkthru-id="18401" target="_blank">Cómo crear una factura de proveedor</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/206509615--C%C3%B3mo-importar-contactos-" class="initWalkthru" data-walktrhu-name="createClient" data-walkthru-id="18066" target="_blank">Cómo importar contactos</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/206512955--C%C3%B3mo-crear-un-Banco-" class="initWalkthru" data-walktrhu-name="createAccount" data-walkthru-id="18065" target="_blank">Cómo crear una cuenta de Banco</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/206509105-Agregar-un-pago-a-una-factura" class="initWalkthru" data-walktrhu-name="createInvoicePayment" data-walkthru-id="18475" target="_blank">Cómo registrar un pago a una cuenta de cobro</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/205798349--C%C3%B3mo-crear-una-Nota-Cr%C3%A9dito-" class="initWalkthru" data-walktrhu-name="createCreditNote" data-walkthru-id="18116" target="_blank">Cómo crear una nota crédito</a></li>
                        </ul>
                    </div>
                    <div id="support" class="box">
                        <h4>Soporte</h4>
                        <ul>
                            <li id="support-link2">Contáctanos</li>
                            <li><a href="http://ayuda.alegra.com/hc/es" target="_blank">Centro de ayuda</a></li>
                            <li><a href="http://www.alegra.com/colombia/manual.pdf" target="_blank">Manual de primeros pasos en Alegra</a></li>
                            <li><a href="http://www.alegra.com/acrecer-con-alegra" target="_blank">Plan de referidos</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/205761789-Caso-de-%C3%A9xito" target="_blank">Comparte tu historia</a></li>
                        </ul>
                    </div>
                    <div id="masAyudas" class="box">
                        <h4>Contactos</h4>
                        <ul>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/206509595--C%C3%B3mo-crear-un-cliente-y-o-proveedor-" target="_blank">¿Cómo crear un Cliente?</a></li>
                            <li><a href="http://ayuda.alegra.com/hc/es/articles/206509615--C%C3%B3mo-importar-contactos-" target="_blank">¿Cómo importar contactos?</a></li>
                        </ul>
                    </div>
                </footer>
            </div>
            <div id="social-modal" class="center-content-vertically">
                <div>
                    <div id="social-media-container">
                        <div class="social-header">
                            <div id="close-media-container">
                                <a id="close-media-link" class="social-media-text">X</a>
                            </div>
                            <div class="social-media-text">
                                <span class="first-text">ALEGRA AYUDA A CRECER TU NEGOCIO</span>
                                <span class="second-text">CUÉNTALE A TUS AMIGOS PARA QUE</span>
                                <span class="third-text">TODOS CREZCAMOS JUNTOS.</span>
                            </div>
                        </div>
                        <div id="social-body">
                            <a class="facebook-share-link" id="ext-gen1044"></a>
                            <a href="https://twitter.com/share" class="twitter-share-link" target="_blank" data-url="http://www.alegra.com" data-text="Con Alegra mi empresa vende más, gana más y crece organizada." data-via="alegraweb" id="ext-gen1045"></a>
                        </div>
                        <div id="social-footer"></div>
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none; visibility: hidden;">
            
            <noscript></noscript>
        </div>
        <div class="x-tip x-layer x-tip-default" id="ext-quicktips-tip" style="display: none;">
            <div class="x-tip-header x-header x-header-horizontal x-docked x-unselectable x-tip-header-default x-horizontal x-tip-header-horizontal x-tip-header-default-horizontal x-top x-tip-header-top x-tip-header-default-top x-docked-top x-tip-header-docked-top x-tip-header-default-docked-top" id="ext-quicktips-tip_header">
                <div id="ext-quicktips-tip_header-body" class="x-header-body x-tip-header-body x-tip-header-body-default x-tip-header-body-horizontal x-tip-header-body-default-horizontal x-tip-header-body-top x-tip-header-body-default-top x-tip-header-body-docked-top x-tip-header-body-default-docked-top x-box-layout-ct x-tip-header-body-default-horizontal x-tip-header-body-default-top x-tip-header-body-default-docked-top">
                    <div id="ext-quicktips-tip_header-innerCt" class="x-box-inner " role="presentation">
                        <div id="ext-quicktips-tip_header-targetEl" class="x-box-target">
                            <div class="x-component x-header-text-container x-tip-header-text-container x-tip-header-text-container-default x-box-item x-component-default" unselectable="on" id="ext-quicktips-tip_header_hd"><span id="ext-quicktips-tip_header_hd-textEl" class="x-header-text x-tip-header-text" unselectable="on">&nbsp;</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="ext-quicktips-tip-body" class="x-tip-body x-tip-body-default x-tip-body-default">
                <span id="ext-quicktips-tip-outerCt" style="display:table;">
                    <div id="ext-quicktips-tip-innerCt" style="display:table-cell;height:100%;vertical-align:top;" class=""></div>
                </span>
            </div>
            <div class="x-tip-anchor x-tip-anchor-top" id="ext-gen1043"></div>
        </div>
        <div class="x-mask" style="z-index: 18999; width: 1014px; height: 325px; right: auto; left: 168px; top: 433px; visibility: hidden;" id="ext-gen1184"></div>
        <div class="x-mask-msg x-layer x-mask-msg-default" id="loadmask-1098" style="right: auto; left: 625px; top: 580px; z-index: 19001; display: none;">
            
        </div>
    </body>
</html>